### ISSUE TITLE
报错uninitialized constant Api::Sys::SysMsgsController

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#5]
2017-04-07 13:33:09 INFO -- Started GET "/api/sys/sys_msgs?token=Wy4PnM5-ZsPXx1sPr9FK" for 58.62.164.189 at 2017-04-07 13:33:09 +0800
2017-04-07 13:33:09 INFO -- Cannot render console from 58.62.164.189! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
2017-04-07 13:33:09 FATAL --   
2017-04-07 13:33:09 FATAL -- ActionController::RoutingError (uninitialized constant Api::Sys::SysMsgsController):
2017-04-07 13:33:09 FATAL --   
2017-04-07 13:33:09 FATAL -- activesupport (5.0.2) lib/active_support/inflector/methods.rb:283:in `const_get'
activesupport (5.0.2) lib/active_support/inflector/methods.rb:283:in `block in constantize'
activesupport (5.0.2) lib/active_support/inflector/methods.rb:266:in `each'
activesupport (5.0.2) lib/active_support/inflector/methods.rb:266:in `inject'
activesupport (5.0.2) lib/active_support/inflector/methods.rb:266:in `constantize'
actionpack (5.0.2) lib/action_dispatch/http/request.rb:81:in `controller_class'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:44:in `controller'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:30:in `serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:725:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.2) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.5.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.0) lib/web_console/middleware.rb:20:in `block in call'
web-console (3.5.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.2) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2017-04-07 13:33:09 INFO --   Rendering /usr/local/rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
2017-04-07 13:33:09 INFO --   Rendering /usr/local/rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
2017-04-07 13:33:09 INFO --   Rendered /usr/local/rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.8ms)
2017-04-07 13:33:09 INFO --   Rendered collection of /usr/local/rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/routes/_route.html.erb [43 times] (12.4ms)
2017-04-07 13:33:09 INFO --   Rendered /usr/local/rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/routes/_table.html.erb (1.2ms)
2017-04-07 13:33:09 INFO --   Rendering /usr/local/rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
2017-04-07 13:33:09 INFO --   Rendered /usr/local/rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.2ms)
2017-04-07 13:33:09 INFO --   Rendered /usr/local/rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (41.8ms)

**Comment by sguo2017** [comment]
提交代码[版本号](https://github.com/sguo2017/tisp_rails_api/commit/866e376f3e68858e85410b10a78abb9ede0fc04f)
